### ISSUE TITLE
Exception running example/parallel.rb

### ISSUE THREAD

**Issue by kevinjalbert** [plataformatec/faraday-http-cache#78]
faraday: 0.9.1
faraday-http-cache: 1.2.2
ruby: 2.2.3p173

I simply cloned the repo, `bundle install`, then `bundle exec ruby ./examples/parallel.rb`.

I received the following exception:

```
HTTP Cache: [GET /repos/plataformatec/faraday-http-cache] miss, store
/Users/jalbert/Projects/faraday-http-cache/lib/faraday/http_cache.rb:156:in `block in call!': undefined method `[]=' for nil:NilClass (NoMethodError)
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.1/lib/faraday/response.rb:64:in `call'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.1/lib/faraday/response.rb:64:in `block in finish'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.1/lib/faraday/response.rb:64:in `each'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.1/lib/faraday/response.rb:64:in `finish'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.1/lib/faraday/adapter/em_http.rb:99:in `block (2 levels) in perform_request'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/eventmachine-1.0.8/lib/em/deferrable.rb:151:in `call'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/eventmachine-1.0.8/lib/em/deferrable.rb:151:in `set_deferred_status'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/eventmachine-1.0.8/lib/em/deferrable.rb:191:in `succeed'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/em-http-request-1.1.2/lib/em-http/client.rb:114:in `unbind'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/em-http-request-1.1.2/lib/em-http/client.rb:71:in `on_request_complete'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:129:in `block in post_init'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:144:in `call'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:144:in `<<'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:144:in `receive_data'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:23:in `receive_data'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.1/lib/faraday/adapter/em_http.rb:202:in `run'
	from /Users/jalbert/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.1/lib/faraday/connection.rb:278:in `in_parallel'
	from ./examples/parallel.rb:15:in `block in <main>'
	from ./examples/parallel.rb:13:in `times'
	from ./examples/parallel.rb:13:in `<main>'
```

I'm not too sure what the root issue is, but it seems that the `response.env` is `nil` after a request is made (https://github.com/plataformatec/faraday-http-cache/blob/master/lib/faraday/http_cache.rb#L156).

**Comment by lucasmazza** [comment]
@kevinjalbert how often did this happened to you? I'm trying to replicate without success so far.

**Comment by kevinjalbert** [comment]
Running with *faraday 0.9.1* and I hit the issue 100% of the time. Running with *faraday 0.9.2* and it works!

A fresh `bundle install` should use 0.9.2 as of today.

I guess this isn't an issue anymore.
